# vim: set ft=ruby :

Vagrant.require_version '>= 1.8.0'

require 'yaml'
require "fileutils"

servers = YAML.load_file('servers.yml')
inventoryPath = 'hosts'

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  # config.ssh.forward_agent = true

  config.vm.box = 'ubuntu/trusty64'
  config.vm.box_check_update = false

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
  end

  f = File.open(inventoryPath,'w')
  f.puts '# autogenerated from servers.yml in Vagrantfile'
  servers.each do |server|
    config.vm.define server['name'] do |srv|

      srv.ssh.port = server['ssh_port']

      srv.vm.hostname = server['name']
      srv.vm.network 'private_network', ip: server['priv_ip']
      server['forwarded_ports'].each do |port|
        srv.vm.network 'forwarded_port', guest: port['guest'], host: port['host']
      end if server['forwarded_ports']
    end
    f.puts server['name'] + ' ansible_host=' + server['priv_ip'] + ' ansible_connection=local'
  end
  f.close

  config.vm.provision 'ansible_local' do |ansible|
    # ansible.verbose = 'vv'
    ansible.playbook = 'ansible/nomadev.yml'
    ansible.galaxy_role_file = 'ansible/requirements.yml'
    ansible.galaxy_roles_path = 'roles-galaxy'
    ansible.inventory_path = inventoryPath
    ansible.sudo = true
  end

end
