# vim: set ft=ruby :

Vagrant.require_version '>= 1.7.4'

require 'yaml'
require "fileutils"

servers = YAML.load_file('servers.yml')

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  config.vm.box = 'ubuntu/trusty64'
  config.vm.box_check_update = false

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
  end

  f = File.open("hosts","w")
  f.puts "# autogenerated from servers.yml in Vagrantfile"
  servers.each do |server|
    config.vm.define server['name'] do |srv|

      srv.ssh.port = server['ssh_port']
      srv.vm.network 'forwarded_port', guest: 22, host: server['ssh_port']

      srv.vm.hostname = server['name']
      srv.vm.network 'private_network', ip: server['priv_ip']
      server['forwarded_ports'].each do |port|
        srv.vm.network 'forwarded_port', guest: port['guest'], host: port['host']
      end if server['forwarded_ports']
    end
    f.puts server["name"] + ' ansible_host=' + server["priv_ip"] + ' ansible_ssh_host=127.0.0.1 ansible_ssh_port=' + server["ssh_port"].to_s
  end
  f.close

  config.vm.provision 'ansible' do |ansible|
    # ansible.verbose = 'vv'
    ansible.playbook = 'ansible/nomadev.yml'
    ansible.inventory_path = 'hosts'
    ansible.sudo = true
  end

end
